apiVersion: v1
kind: Service
metadata:
  name: webook-redis
spec:
  selector:
    app: webook-redis
  ports:
    - protocol: TCP
      # k8s internal port
      port: 6379
      # external access ports, must between 30000 - 32767
      nodePort: 31379
      # pod expose port
      targetPort: 6379
  type: NodePort
  # export the port for external access
  